/// One row per Copilot Studio conversation (Dataverse conversationtranscript
/// record). Aggregates from message/event/trace activities. Built by
/// parse_copilot_transcripts.py. In Fabric this comes from the lakehouse
/// Delta table `agent_sessions`.
table 'Agent Sessions'
	lineageTag: ag0001se-0001-0001-0001-000000000001

	/// Total conversations in scope. Each row = one Dataverse conversationtranscript record.
	measure 'Transcript Sessions' = COUNTROWS('Agent Sessions')
		formatString: #,0
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000001

	/// Distinct end users (hashed) who held at least one conversation.
	measure 'Transcript Active Users' = DISTINCTCOUNT('Agent Sessions'[user_id_hash])
		formatString: #,0
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000002

	/// Average duration of a conversation in seconds.
	measure 'Avg Session Duration (sec)' = DIVIDE(AVERAGE('Agent Sessions'[session_duration_ms]), 1000)
		formatString: #,0.0
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000003

	/// Sum of total_displayed_cost across all sessions (in-product cost units, not money).
	measure 'Total Cost Units' = SUM('Agent Sessions'[total_displayed_cost])
		formatString: #,0
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000004
		annotation PBI_FormatHint = {"isDecimal":true}

	/// Resolves each credit session's user (AAD objectId in user_id_hash) to an Organization. Unmatched
	/// users surface as "(Unmapped)" so cross-tenant / cross-environment identity mismatches are visible
	/// instead of silently inflating every org's share; matched users with no department show "(No Department)".
	column 'Credit User Org' = VAR _matched = NOT ISBLANK ( RELATED ( 'Chat + Agent Org Data'[PersonId] ) ) RETURN IF ( _matched, COALESCE ( RELATED ( 'Chat + Agent Org Data'[Organization] ), "(No Department)" ), "(Unmapped)" )
		lineageTag: ag0001se-col0-credituserorg01
		summarizeBy: none
		dataType: string

	/// Credit units that could NOT be attributed to any organization (user objectId absent from Org data).
	measure 'Unmapped Credit Units' = CALCULATE ( [Total Cost Units], 'Agent Sessions'[Credit User Org] = "(Unmapped)" )
		formatString: #,0
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-unmappedcu01

	/// Share of credit units not attributed to an org. High => identity mismatch (transcripts from a
	/// different environment/tenant than the Entra org data).
	measure 'Unmapped Credit %' = DIVIDE ( [Unmapped Credit Units], [Total Cost Units] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-unmappedpct1

	/// Credit units successfully attributed to an organization.
	measure 'Mapped Credit Units' = [Total Cost Units] - [Unmapped Credit Units]
		formatString: #,0
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-mappedcu01

	/// Mean cost per conversation.
	measure 'Avg Cost per Session' = AVERAGE('Agent Sessions'[total_displayed_cost])
		formatString: #,0.00
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000005

	/// % of sessions where the bot fired at least one error trace.
	measure 'Session Error Rate' =
			VAR _err = CALCULATE(COUNTROWS('Agent Sessions'), 'Agent Sessions'[error_count] > 0)
			VAR _tot = COUNTROWS('Agent Sessions')
			RETURN DIVIDE(_err, _tot)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000006

	/// Mean number of messages (user + bot) per session.
	measure 'Avg Turns per Session' = AVERAGE('Agent Sessions'[msg_count])
		formatString: #,0.0
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000007

	/// % of sessions where the agent searched its knowledge sources.
	measure 'Knowledge Search Rate' =
			VAR _hit = CALCULATE(COUNTROWS('Agent Sessions'), 'Agent Sessions'[knowledge_searched] = TRUE())
			RETURN DIVIDE(_hit, COUNTROWS('Agent Sessions'))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 📚 Prompt Quality
		lineageTag: ag0001se-meas-0001-000000000008

	/// % of sessions where the knowledge search returned a citable answer.
	measure 'Knowledge Answered Rate' =
			VAR _hit = CALCULATE(COUNTROWS('Agent Sessions'), 'Agent Sessions'[knowledge_answered] = TRUE())
			RETURN DIVIDE(_hit, COUNTROWS('Agent Sessions'))
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 📚 Prompt Quality
		lineageTag: ag0001se-meas-0001-000000000009

	/// Total sub-agent invocations across all sessions.
	measure 'Total Connected Agent Calls' = SUM('Agent Sessions'[connected_agent_count])
		formatString: #,0
		displayFolder: 🤖 Agent Performance
		lineageTag: ag0001se-meas-0001-000000000010

	/// Distinct agents that consumed at least one credit unit.
	measure 'Agents with Credits' = CALCULATE(DISTINCTCOUNT('Agent Sessions'[primary_agent_schema]), 'Agent Sessions'[total_displayed_cost] > 0)
		formatString: #,0
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000021

	/// Mean credit units per agent (total credits / distinct agents that consumed credits).
	measure 'Avg Credits per Agent' =
			DIVIDE(
			    [Total Cost Units],
			    CALCULATE(DISTINCTCOUNT('Agent Sessions'[primary_agent_schema]), 'Agent Sessions'[total_displayed_cost] > 0)
			)
		formatString: #,0.00
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000022

	/// Credit units consumed by the single biggest-spending agent.
	measure 'Max Agent Credits' =
			MAXX(
			    VALUES('Agent Sessions'[primary_agent_schema]),
			    CALCULATE([Total Cost Units])
			)
		formatString: #,0.00
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000023

	/// Share of all credits taken by the agents currently in filter context.
	measure 'Credit Share %' =
			DIVIDE(
			    [Total Cost Units],
			    CALCULATE([Total Cost Units], ALL('Agent Sessions'[primary_agent_schema]))
			)
		formatString: 0%;-0%;0%
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000024

	/// Sessions where a feedback card was shown to the user (the *offered* signal — not a verdict).
	measure 'Sessions with Feedback Prompt' = CALCULATE(COUNTROWS('Agent Sessions'), 'Agent Sessions'[feedback_offered_count] > 0)
		formatString: #,0
		displayFolder: 💬 Feedback Signal
		lineageTag: ag0001se-meas-0001-000000000030

	/// Share of sessions that surfaced a feedback prompt.
	measure 'Feedback Prompt Rate' =
			DIVIDE(
			    [Sessions with Feedback Prompt],
			    [Transcript Sessions]
			)
		formatString: 0%;-0%;0%
		displayFolder: 💬 Feedback Signal
		lineageTag: ag0001se-meas-0001-000000000031

	/// Sessions where the user actually SUBMITTED a thumbs verdict (completed feedback).
	measure 'Sessions with Submitted Feedback' = SUM('Agent Sessions'[feedback_submitted])
		formatString: #,0
		displayFolder: 💬 Feedback Signal
		lineageTag: ag0001se-meas-0001-000000000032

	/// Submitted thumbs-up sessions (transcript-native).
	measure 'Transcript Thumbs Up' = CALCULATE(COUNTROWS('Agent Sessions'), 'Agent Sessions'[feedback_verdict] = "Positive")
		formatString: #,0
		displayFolder: 💬 Feedback Signal
		lineageTag: ag0001se-meas-0001-000000000033

	/// Submitted thumbs-down sessions (transcript-native).
	measure 'Transcript Thumbs Down' = CALCULATE(COUNTROWS('Agent Sessions'), 'Agent Sessions'[feedback_verdict] = "Negative")
		formatString: #,0
		displayFolder: 💬 Feedback Signal
		lineageTag: ag0001se-meas-0001-000000000034

	/// Transcript-native CSAT: submitted thumbs-up / all submitted verdicts. Lights up automatically when an export carries completed reactions.
	measure 'Transcript CSAT Score' =
			DIVIDE(
			    [Transcript Thumbs Up],
			    [Transcript Thumbs Up] + [Transcript Thumbs Down]
			)
		formatString: 0%;-0%;0%
		displayFolder: 💬 Feedback Signal
		lineageTag: ag0001se-meas-0001-000000000035

	/// Share of feedback-prompted sessions where the user actually submitted a verdict (completion rate).
	measure 'Feedback Submission Rate' =
			DIVIDE(
			    [Sessions with Submitted Feedback],
			    [Sessions with Feedback Prompt]
			)
		formatString: 0%;-0%;0%
		displayFolder: 💬 Feedback Signal
		lineageTag: ag0001se-meas-0001-000000000036

	/// Each organization's share of total credit spend across the full population (denominator ignores the org row, respects other slicers like Date).
	measure 'Org Credit Share %' =
			DIVIDE(
			    [Total Cost Units],
			    CALCULATE(
			        [Total Cost Units],
			        ALL('Chat + Agent Org Data')
			    )
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000025

	/// Mean credit units per distinct end user who consumed credits (total credits / users with spend > 0).
	measure 'Avg Credits per User' =
			DIVIDE(
			    [Total Cost Units],
			    CALCULATE(
			        DISTINCTCOUNT('Agent Sessions'[user_id_hash]),
			        'Agent Sessions'[total_displayed_cost] > 0
			    )
			)
		formatString: #,0.00
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000026

	/// Organisation with the highest credits-per-user ratio (respects all other slicers). Ignores orgs with no credit-consuming users.
	measure 'Top Org by Credits per User' =
			VAR _ranked =
			    ADDCOLUMNS(
			        VALUES('Chat + Agent Org Data'[Organization]),
			        "@CreditsPerUser", [Avg Credits per User]
			    )
			VAR _withSpend = FILTER(_ranked, NOT ISBLANK([@CreditsPerUser]) && [@CreditsPerUser] > 0)
			RETURN
			    MAXX(
			        TOPN(1, _withSpend, [@CreditsPerUser], DESC),
			        'Chat + Agent Org Data'[Organization]
			    )
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000027

	/// The credits-per-user value for the organisation returned by [Top Org by Credits per User].
	measure 'Top Org Credits per User (Value)' =
			VAR _ranked =
			    ADDCOLUMNS(
			        VALUES('Chat + Agent Org Data'[Organization]),
			        "@CreditsPerUser", [Avg Credits per User]
			    )
			VAR _withSpend = FILTER(_ranked, NOT ISBLANK([@CreditsPerUser]) && [@CreditsPerUser] > 0)
			RETURN
			    MAXX(
			        TOPN(1, _withSpend, [@CreditsPerUser], DESC),
			        [@CreditsPerUser]
			    )
		formatString: #,0.00
		displayFolder: 💳 Credits
		lineageTag: ag0001se-meas-0001-000000000028

	column conversation_id
		dataType: string
		isKey
		lineageTag: ag0001se-col0-0001-000000000001
		summarizeBy: none
		sourceColumn: conversation_id

		annotation SummarizationSetBy = Automatic

	column session_start_utc
		dataType: dateTime
		formatString: General Date
		lineageTag: ag0001se-col0-0001-000000000002
		summarizeBy: none
		sourceColumn: session_start_utc

		annotation SummarizationSetBy = Automatic

	/// Derived date for joining to Calendar table.
	column 'Session Start Date' = DATEVALUE('Agent Sessions'[session_start_utc])
		dataType: dateTime
		formatString: Short Date
		lineageTag: ag0001se-col0-0001-000000000003
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column session_duration_ms
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000004
		summarizeBy: sum
		sourceColumn: session_duration_ms

		annotation SummarizationSetBy = Automatic

	column user_id_hash
		dataType: string
		lineageTag: ag0001se-col0-0001-000000000005
		summarizeBy: none
		sourceColumn: user_id_hash

		annotation SummarizationSetBy = Automatic

	column primary_agent_schema
		dataType: string
		lineageTag: ag0001se-col0-0001-000000000006
		summarizeBy: none
		sourceColumn: primary_agent_schema

		annotation SummarizationSetBy = Automatic

	column connected_agent_schemas
		dataType: string
		lineageTag: ag0001se-col0-0001-000000000007
		summarizeBy: none
		sourceColumn: connected_agent_schemas

		annotation SummarizationSetBy = Automatic

	column connected_agent_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000008
		summarizeBy: sum
		sourceColumn: connected_agent_count

		annotation SummarizationSetBy = Automatic

	column msg_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000009
		summarizeBy: sum
		sourceColumn: msg_count

		annotation SummarizationSetBy = Automatic

	column user_msg_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000010
		summarizeBy: sum
		sourceColumn: user_msg_count

		annotation SummarizationSetBy = Automatic

	column bot_msg_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000011
		summarizeBy: sum
		sourceColumn: bot_msg_count

		annotation SummarizationSetBy = Automatic

	column plan_step_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000012
		summarizeBy: sum
		sourceColumn: plan_step_count

		annotation SummarizationSetBy = Automatic

	column total_displayed_cost
		dataType: double
		formatString: #,0.00
		lineageTag: ag0001se-col0-0001-000000000013
		summarizeBy: sum
		sourceColumn: total_displayed_cost

		annotation SummarizationSetBy = Automatic

	column total_latency_ms
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000014
		summarizeBy: sum
		sourceColumn: total_latency_ms

		annotation SummarizationSetBy = Automatic

	column knowledge_searched
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ag0001se-col0-0001-000000000015
		summarizeBy: none
		sourceColumn: knowledge_searched

		annotation SummarizationSetBy = Automatic

	column knowledge_answered
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ag0001se-col0-0001-000000000016
		summarizeBy: none
		sourceColumn: knowledge_answered

		annotation SummarizationSetBy = Automatic

	column knowledge_sources_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000017
		summarizeBy: sum
		sourceColumn: knowledge_sources_count

		annotation SummarizationSetBy = Automatic

	column error_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000018
		summarizeBy: sum
		sourceColumn: error_count

		annotation SummarizationSetBy = Automatic

	column first_error_code
		dataType: string
		lineageTag: ag0001se-col0-0001-000000000019
		summarizeBy: none
		sourceColumn: first_error_code

		annotation SummarizationSetBy = Automatic

	column feedback_offered_count
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000020
		summarizeBy: sum
		sourceColumn: feedback_offered_count

		annotation SummarizationSetBy = Automatic

	column first_user_prompt
		dataType: string
		lineageTag: ag0001se-col0-0001-000000000021
		summarizeBy: none
		sourceColumn: first_user_prompt

		annotation SummarizationSetBy = Automatic

	column feedback_submitted
		dataType: int64
		formatString: 0
		lineageTag: ag0001se-col0-0001-000000000022
		summarizeBy: sum
		sourceColumn: feedback_submitted

		annotation SummarizationSetBy = Automatic

	column feedback_verdict
		dataType: string
		lineageTag: ag0001se-col0-0001-000000000023
		summarizeBy: none
		sourceColumn: feedback_verdict

		annotation SummarizationSetBy = Automatic

	column feedback_comment
		dataType: string
		lineageTag: ag0001se-col0-0001-000000000024
		summarizeBy: none
		sourceColumn: feedback_comment

		annotation SummarizationSetBy = Automatic

	partition 'Agent Sessions' = m
		mode: import
		source =
				let
				    Promoted = if Enable_Dataverse then (try FabricTable("agent_sessions") otherwise EmptyTable({"conversation_id", "session_start_utc", "session_duration_ms", "user_id_hash", "primary_agent_schema", "connected_agent_schemas", "connected_agent_count", "msg_count", "user_msg_count", "bot_msg_count", "plan_step_count", "total_displayed_cost", "total_latency_ms", "knowledge_searched", "knowledge_answered", "knowledge_sources_count", "error_count", "first_error_code", "feedback_offered_count", "feedback_submitted", "feedback_verdict", "feedback_comment", "first_user_prompt"})) else EmptyTable({"conversation_id", "session_start_utc", "session_duration_ms", "user_id_hash", "primary_agent_schema", "connected_agent_schemas", "connected_agent_count", "msg_count", "user_msg_count", "bot_msg_count", "plan_step_count", "total_displayed_cost", "total_latency_ms", "knowledge_searched", "knowledge_answered", "knowledge_sources_count", "error_count", "first_error_code", "feedback_offered_count", "feedback_submitted", "feedback_verdict", "feedback_comment", "first_user_prompt"}),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"conversation_id", type text},
				        {"session_start_utc", type datetime},
				        {"session_duration_ms", Int64.Type},
				        {"user_id_hash", type text},
				        {"primary_agent_schema", type text},
				        {"connected_agent_schemas", type text},
				        {"connected_agent_count", Int64.Type},
				        {"msg_count", Int64.Type},
				        {"user_msg_count", Int64.Type},
				        {"bot_msg_count", Int64.Type},
				        {"plan_step_count", Int64.Type},
				        {"total_displayed_cost", type number},
				        {"total_latency_ms", Int64.Type},
				        {"knowledge_searched", type logical},
				        {"knowledge_answered", type logical},
				        {"knowledge_sources_count", Int64.Type},
				        {"error_count", Int64.Type},
				        {"first_error_code", type text},
				        {"feedback_offered_count", Int64.Type},
				        {"feedback_submitted", Int64.Type},
				        {"feedback_verdict", type text},
				        {"feedback_comment", type text},
				        {"first_user_prompt", type text}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table

