table 'AI PPUPM'
	lineageTag: ad544143-3002-42e4-888b-6eda41b83c04

	measure 'AI PPUPM Value' = SELECTEDVALUE('AI PPUPM'[AI PPUPM], 30)
		formatString: 0
		lineageTag: 0210af26-a0e0-4d8a-b931-fbc56d193547

	measure 'Reinvestment Rate (Forrester TEI)' = ```
			0.50
			
			```
		lineageTag: 230510a9-87f2-4ded-ae8b-e9bac6e95081

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Productive Capacity - Hours Per Week' = ```
			
			    [Efficiency - Hours Per Week] * [Reinvestment Rate (Forrester TEI)]
			
			```
		lineageTag: 37f06f2c-52d5-4a0a-89a9-80b6b06a0b2e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AI PPUPM'
		formatString: 0
		lineageTag: 8fb4393f-7107-4381-9fe6-f59e999525fa
		summarizeBy: none
		sourceColumn: [Value]

		extendedProperty ParameterMetadata =
				{
				  "version": 0
				}

		annotation SummarizationSetBy = User

	partition 'AI PPUPM' = calculated
		mode: import
		source = GENERATESERIES(0, 30, 1)

	annotation PBI_Id = 0841d4f5cbb540b1b2378797bc49b76a

