table Headlines
	isHidden
	lineageTag: ff0a0001-0001-0001-0001-000000000001

	/// Executive summary headline. Pattern C: plain-English insight then metrics with bold digits.
	measure 'Executive Headline' =
			VAR Tsk        = [AI Tasks]
			VAR HpW        = [Efficiency - Hours Per Week]
			VAR WrkPerWeek = [Work Created - Per Week]
			VAR Roles      = [New Expertise - Roles]
			VAR LF         = UNICHAR(10)
			VAR Insight    =
			    SWITCH(
			        TRUE(),
			        HpW = 0,         "No measurable AI productivity in this view",
			        HpW >= 5000,     "AI is delivering material weekly productivity across the org",
			        HpW >= 1000,     "AI is delivering steady weekly productivity",
			        "AI productivity is at an early, exploratory stage"
			    )
			VAR RawMetrics =
			    FORMAT(Tsk, "#,##0") & " AI tasks  ·  " &
			    FORMAT(HpW, "#,##0") & " hours saved per week  ·  " &
			    FORMAT(WrkPerWeek, "#,##0") & " work items created  ·  " &
			    FORMAT(Roles, "#,##0") & " specialist roles unlocked"
			VAR Metrics =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(
			        RawMetrics,
			        "0", UNICHAR(120812)),
			        "1", UNICHAR(120813)),
			        "2", UNICHAR(120814)),
			        "3", UNICHAR(120815)),
			        "4", UNICHAR(120816)),
			        "5", UNICHAR(120817)),
			        "6", UNICHAR(120818)),
			        "7", UNICHAR(120819)),
			        "8", UNICHAR(120820)),
			        "9", UNICHAR(120821))
			RETURN Insight & LF & Metrics
		displayFolder: Headlines
		lineageTag: ff0a0001-0001-0001-0001-000000000010

	/// User Maturity - By Organisation. Pattern C: plain-English insight then metrics with bold digits.
	/// 16 May 2026 — upgraded for 5-stage Maturity ladder. "Power" is the new top stage.
	measure 'Maturity By Org Headline' =
			VAR TotalOrgs     = DISTINCTCOUNT('Chat + Agent Org Data'[Organization])
			VAR OrgsWithPower = CALCULATE(DISTINCTCOUNT('Chat + Agent Org Data'[Organization]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "4 - Power")
			VAR PowerPct      = [Power Users %]
			VAR HabPowPct     = [Habitual + Power %]
			VAR LF            = UNICHAR(10)
			VAR Insight       =
			    SWITCH(
			        TRUE(),
			        PowerPct = 0 && HabPowPct = 0, "No habit-stage users yet — adoption is still in early exploration",
			        PowerPct >= 0.15,              "A strong share of users have reached Power stage — champions are visible",
			        HabPowPct >= 0.25,             "Habitual & Power users are forming a critical mass",
			        HabPowPct >= 0.10,             "Habitual & Power users are emerging — momentum building",
			        "Most users are still early on the maturity curve"
			    )
			VAR RawMetrics =
			    FORMAT(OrgsWithPower, "0") & " of " & FORMAT(TotalOrgs, "0") & " organisations have Power users  ·  " &
			    FORMAT(HabPowPct, "0%") & " of users at Habitual or Power stage"
			VAR Metrics =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(
			        RawMetrics,
			        "0", UNICHAR(120812)),
			        "1", UNICHAR(120813)),
			        "2", UNICHAR(120814)),
			        "3", UNICHAR(120815)),
			        "4", UNICHAR(120816)),
			        "5", UNICHAR(120817)),
			        "6", UNICHAR(120818)),
			        "7", UNICHAR(120819)),
			        "8", UNICHAR(120820)),
			        "9", UNICHAR(120821))
			RETURN Insight & LF & Metrics
		displayFolder: Headlines\Maturity
		lineageTag: ff0a0001-0001-0001-0001-000000000023

	/// User Maturity - Task Breakdown. Pattern C: plain-English insight then metrics with bold digits.
	/// 16 May 2026 — compares the bottom stage (Beginner) with the top stage (Power) on breadth of tasks.
	measure 'Maturity Task Breakdown Headline' =
			VAR BeginnerAvg = AVERAGEX(
			    CALCULATETABLE(VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "1 - Beginner"),
			    CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown]))
			)
			VAR PowerAvg = AVERAGEX(
			    CALCULATETABLE(VALUES('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "4 - Power"),
			    CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Efficiency_Breakdown]))
			)
			VAR Multi   = DIVIDE(PowerAvg, BeginnerAvg, 0)
			VAR LF      = UNICHAR(10)
			VAR Insight =
			    SWITCH(
			        TRUE(),
			        BeginnerAvg = 0 && PowerAvg = 0, "No task data in this view",
			        Multi >= 2,                       "Power users tackle a much broader range of tasks than Beginners",
			        Multi >= 1.3,                     "Power users handle noticeably more task types than Beginners",
			        "Beginners and Power users tackle a similar range of tasks"
			    )
			VAR RawMetrics =
			    "Beginners avg " & FORMAT(BeginnerAvg, "0.0") & " task types  ·  Power avg " & FORMAT(PowerAvg, "0.0") & " task types  ·  " &
			    FORMAT(Multi, "0.0") & "x the breadth"
			VAR Metrics =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(
			        RawMetrics,
			        "0", UNICHAR(120812)),
			        "1", UNICHAR(120813)),
			        "2", UNICHAR(120814)),
			        "3", UNICHAR(120815)),
			        "4", UNICHAR(120816)),
			        "5", UNICHAR(120817)),
			        "6", UNICHAR(120818)),
			        "7", UNICHAR(120819)),
			        "8", UNICHAR(120820)),
			        "9", UNICHAR(120821))
			RETURN Insight & LF & Metrics
		displayFolder: Headlines\Maturity
		lineageTag: ff0a0001-0001-0001-0001-000000000025

	/// User Maturity - Specialist Roles. Pattern C: plain-English insight then metrics with bold digits.
	/// 16 May 2026 — refactored to 5-stage Maturity ladder. "Power" cohort is the new specialist benchmark.
	measure 'Maturity Specialist Headline' =
			VAR BeginnerRoles = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "1 - Beginner", NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR DevelopingRoles  = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "2 - Developing", NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR HabitualRoles    = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "3 - Habitual",    NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR PowerRoles    = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Expertise_Role]), 'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "4 - Power",    NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR PowerTotal    = CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),  'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "4 - Power")
			VAR PowerExpertUsr= CALCULATE(DISTINCTCOUNT('Chat + Agent Interactions (Audit Logs)'[Audit_UserId]),  'Chat + Agent Interactions (Audit Logs)'[User_Stage_Maturity] = "4 - Power", NOT(ISBLANK('Chat + Agent Interactions (Audit Logs)'[Expertise_Role])))
			VAR PowerExpertPct= DIVIDE(PowerExpertUsr, PowerTotal, 0)
			VAR LF            = UNICHAR(10)
			VAR Insight       =
			    SWITCH(
			        TRUE(),
			        PowerExpertPct = 0,        "No specialist AI expertise is being tapped yet",
			        PowerExpertPct >= 0.30,    "Power users routinely tap specialist AI expertise",
			        PowerExpertPct >= 0.10,    "A growing share of Power users access specialist AI expertise",
			        "Specialist AI expertise is only tapped by a small group"
			    )
			VAR RawMetrics =
			    "Beginner " & FORMAT(BeginnerRoles, "0") & " roles  ·  Developing " & FORMAT(DevelopingRoles, "0") & " roles  ·  Habitual " & FORMAT(HabitualRoles, "0") & " roles  ·  Power " & FORMAT(PowerRoles, "0") & " roles  ·  " &
			    FORMAT(PowerExpertPct, "0%") & " of Power users tap specialist expertise"
			VAR Metrics =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(
			        RawMetrics,
			        "0", UNICHAR(120812)),
			        "1", UNICHAR(120813)),
			        "2", UNICHAR(120814)),
			        "3", UNICHAR(120815)),
			        "4", UNICHAR(120816)),
			        "5", UNICHAR(120817)),
			        "6", UNICHAR(120818)),
			        "7", UNICHAR(120819)),
			        "8", UNICHAR(120820)),
			        "9", UNICHAR(120821))
			RETURN Insight & LF & Metrics
		displayFolder: Headlines\Maturity
		lineageTag: ff0a0001-0001-0001-0001-000000000026

	/// License Readiness / Priority Ranking page headline. Pattern C: plain-English insight then metrics with bold digits.
	measure 'License Priority Headline' =
			VAR UnlUsers     = [NoOfActiveChatUsers (Unlicensed)]
			VAR UnlOrgs      = CALCULATE(DISTINCTCOUNT('Chat + Agent Org Data'[Organization]), 'Chat + Agent Interactions (Audit Logs)'[License Status] = "Unlicensed")
			VAR UnlTasksPUPW = [Median Unlicensed AI Tasks Per User Per Week]
			VAR LF           = UNICHAR(10)
			VAR Insight      =
			    SWITCH(
			        TRUE(),
			        UnlUsers = 0,            "No unlicensed AI activity in the current view.",
			        UnlTasksPUPW >= 5,       "Heavy use by unlicensed users — give these people a Copilot licence first.",
			        UnlTasksPUPW >= 2,       "Steady use by unlicensed users — line them up as your next licence wave.",
			        "Light use by unlicensed users — let activity grow before assigning licences."
			    )
			VAR RawMetrics =
			    FORMAT(UnlUsers, "#,##0") & " unlicensed active users  ·  " & FORMAT(UnlOrgs, "#,##0") & " organisations  ·  " &
			    FORMAT(UnlTasksPUPW, "#,##0.0") & " median AI tasks per user per week"
			VAR Metrics =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(
			        RawMetrics,
			        "0", UNICHAR(120812)),
			        "1", UNICHAR(120813)),
			        "2", UNICHAR(120814)),
			        "3", UNICHAR(120815)),
			        "4", UNICHAR(120816)),
			        "5", UNICHAR(120817)),
			        "6", UNICHAR(120818)),
			        "7", UNICHAR(120819)),
			        "8", UNICHAR(120820)),
			        "9", UNICHAR(120821))
			RETURN Insight & LF & Metrics
		displayFolder: Headlines\License
		lineageTag: ff0a0001-0001-0001-0001-000000000040

	/// Skills Headline — UNIFIED Pattern-C headline for augmented skills.
	/// 17 May 2026 — replaces the separate `Copilot Skills Headline` and `Agent Skills Headline`.
	/// One measure that dynamically narrates the current cohort (Licensed / Unlicensed / Agents / mixed)
	/// using two signals from the filter context:
	/// • Breadth         — Avg Skills Per User (how many distinct AI-augmented skills the cohort uses)
	/// • Specialist depth — New Expertise - Users / Roles (how many people reach into specialist roles)
	/// 
	/// Cohort is detected from the Environment slicer ([License Status]-derived) and the Agent Filter slicer.
	/// The opening clause of the insight always names the cohort plainly, so the headline reads correctly
	/// whether the page is unfiltered, on Licensed, on Unlicensed, on Agents, or any combination.
	measure 'Skills Headline' =
			VAR AvgSkills    = [Avg Skills Per User]
			VAR ExpertRoles  = [New Expertise - Roles]
			VAR ExpertUsers  = [New Expertise - Users]
			-- Cohort detection from existing slicer columns
			VAR EnvSel       = SELECTEDVALUE('Chat + Agent Interactions (Audit Logs)'[Environment])
			VAR AgentSel     = SELECTEDVALUE('Chat + Agent Interactions (Audit Logs)'[Agent Filter])
			VAR IsAgentSlice = AgentSel = "Agents"
			VAR Cohort =
			    SWITCH(
			        TRUE(),
			        IsAgentSlice && EnvSel = "Licensed",   "Licensed agent users",
			        IsAgentSlice && EnvSel = "Unlicensed", "Unlicensed agent users",
			        IsAgentSlice,                          "Agent users",
			        EnvSel = "Licensed",                   "Licensed Copilot users",
			        EnvSel = "Unlicensed",                 "Unlicensed Copilot users",
			        EnvSel = "Cowork",                     "Cowork users",
			        "Copilot & agent users"
			    )
			VAR LF = UNICHAR(10)
			VAR Insight =
			    SWITCH(
			        TRUE(),
			        AvgSkills = 0 && ExpertUsers = 0,
			            Cohort & " have not yet tapped AI-augmented skills in this view",
			        AvgSkills >= 5 && ExpertUsers >= 50,
			            Cohort & " tap a broad set of AI skills and routinely reach specialist expertise",
			        AvgSkills >= 5,
			            Cohort & " tap a broad set of AI-augmented skills",
			        ExpertUsers >= 50,
			            Cohort & " regularly reach specialist AI expertise via agents",
			        AvgSkills >= 3,
			            Cohort & " are reaching beyond a few core skills",
			        ExpertUsers >= 10,
			            Cohort & " are starting to access specialist agent expertise",
			        Cohort & " use a small set of core AI skills — room to broaden"
			    )
			VAR RawMetrics =
			    FORMAT(AvgSkills, "#,##0.0") & " avg skill types per user  ·  " &
			    FORMAT(ExpertRoles, "0") & " specialist roles tapped by " & FORMAT(ExpertUsers, "#,##0") & " users"
			VAR Metrics =
			    SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(
			        RawMetrics,
			        "0", UNICHAR(120812)),
			        "1", UNICHAR(120813)),
			        "2", UNICHAR(120814)),
			        "3", UNICHAR(120815)),
			        "4", UNICHAR(120816)),
			        "5", UNICHAR(120817)),
			        "6", UNICHAR(120818)),
			        "7", UNICHAR(120819)),
			        "8", UNICHAR(120820)),
			        "9", UNICHAR(120821))
			RETURN Insight & LF & Metrics
		displayFolder: Headlines
		lineageTag: ff0a0001-0001-0001-0001-000000000041

	column Placeholder
		lineageTag: 6dd949b7-b523-4a00-be54-69752cc60699
		isNameInferred
		sourceColumn: [Placeholder]

	partition Headlines = calculated
		mode: import
		source = ROW("Placeholder", 1)
