table 'Agent Performance'
	lineageTag: 448eb627-6701-4335-8f1e-cb626f4e7c9b

	measure 'Total Conversations' = COUNTROWS('Agent Performance')
		formatString: #,0
		displayFolder: Agent KPIs
		lineageTag: e4a91aa9-b95f-494b-8538-ec1515db44e5

	measure 'Abandonment Rate' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('Agent Performance'),
			        'Agent Performance'[SessionOutcome] = "Abandoned"
			    ),
			    COUNTROWS('Agent Performance'),
			    0
			)
		formatString: 0.0%
		displayFolder: Agent KPIs
		lineageTag: 2464f6a3-c461-42bc-94cd-f5f828635fee

	measure 'Avg Conversation Duration' = AVERAGE('Agent Performance'[DurationSeconds])
		formatString: #,0 "sec"
		displayFolder: Agent KPIs
		lineageTag: 773d08ba-6f32-48ac-a60f-ce8f41e10b3f

	measure 'Resolution Rate' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('Agent Performance'),
			        'Agent Performance'[SessionOutcome] = "Resolved"
			    ),
			    COUNTROWS('Agent Performance'),
			    0
			)
		formatString: 0.0%
		displayFolder: Agent KPIs
		lineageTag: e49bd491-1a0a-4114-9b19-22c4e5bb18f2

	measure 'Unique Users' = DISTINCTCOUNT('Agent Performance'[Var_ESS_UserContext_UPN])
		formatString: #,0
		displayFolder: Agent KPIs
		lineageTag: 64c70052-af52-498e-a35f-ddca55f4940a

	/// % of conversations the orchestrator flagged as impliedSuccess=TRUE. The reliable
	/// proxy-satisfaction signal when explicit thumbs are too sparse for a CSAT.
	measure 'Implied Success %' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('Agent Performance'),
			        'Agent Performance'[ImpliedSuccess] = "TRUE"
			    ),
			    COUNTROWS('Agent Performance'),
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Agent KPIs
		lineageTag: e49bd491-1a0a-4114-9b19-22c4e5bb1900

	measure 'Avg Bot Response Time' = AVERAGE('Agent Performance'[AverageLatencyMs])
		formatString: #,0 "ms"
		displayFolder: Agent Performance
		lineageTag: 9de05fa2-9b96-4379-be5d-fd41280196a7

	measure 'Escalation Rate' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('Agent Performance'),
			        'Agent Performance'[SessionOutcome] = "Escalated"
			    ),
			    COUNTROWS('Agent Performance'),
			    0
			)
		formatString: 0.0%
		displayFolder: Agent KPIs
		lineageTag: e484b66c-978b-42ed-8f63-71488721da77

	/// Avg turns needed to resolve — lower = better prompt clarity
	measure 'Avg Turns to Resolve' =
			CALCULATE(
			    AVERAGE('Agent Performance'[TurnCount]),
			    'Agent Performance'[SessionOutcome] = "Resolved"
			)
		formatString: 0.0
		displayFolder: 🧠 Prompt Quality
		lineageTag: b1c2d3e4-0001-0001-0003-000000000001

	/// Avg Prompt Quality Score across current filter context (0–100)
	measure 'Avg Prompt Quality Score' = AVERAGE('Agent Performance'[PromptQualityScore])
		formatString: 0.0
		displayFolder: 🧠 Prompt Quality
		lineageTag: b1c2d3e4-0001-0001-0001-000000000001

	/// % of engaged conversations where the first message led to resolution in ≤ 4 turns
	measure 'Prompt Effectiveness Rate' =
			DIVIDE(
			    CALCULATE(
			        COUNTROWS('Agent Performance'),
			        'Agent Performance'[SessionOutcome] = "Resolved",
			        'Agent Performance'[TurnCount] <= 4,
			        'Agent Performance'[SessionType] = "Engaged"
			    ),
			    CALCULATE(
			        COUNTROWS('Agent Performance'),
			        'Agent Performance'[SessionType] = "Engaged"
			    ),
			    0
			)
		formatString: 0.0%
		displayFolder: 🧠 Prompt Quality
		lineageTag: b1c2d3e4-0001-0001-0002-000000000001

	measure 'Avg Topics Per Conversation' = AVERAGE('Agent Performance'[TopicCount])
		formatString: 0.0
		displayFolder: Agent KPIs
		lineageTag: b1c2d3e4-0001-0001-0006-000000000001

	/// Average conversation complexity (0–5 scale: Unengaged=0, Quick Info=1, Standard=2, Troubleshooting=3, Extended=4, Multi-Topic=5)
	measure 'Avg Conversation Complexity' = AVERAGE('Agent Performance'[ConversationComplexity])
		formatString: 0.0
		displayFolder: 🧠 Prompt Quality
		lineageTag: b1c2d3e4-0001-0002-0001-000000000001

	/// Most common conversation type for the current filter context (agent, date, etc.)
	measure 'Dominant Conversation Type' =
			VAR TypeCounts =
			    ADDCOLUMNS(
			        VALUES('Agent Performance'[ConversationType]),
			        "TypeTotal", CALCULATE(COUNTROWS('Agent Performance'))
			    )
			VAR TopType = TOPN(1, TypeCounts, [TypeTotal], DESC)
			VAR TopName = MAXX(TopType, [ConversationType])
			VAR TopTypeCount = MAXX(TopType, [TypeTotal])
			VAR Total = COUNTROWS('Agent Performance')
			RETURN
			IF(Total = 0, BLANK(),
			    TopName & " (" & FORMAT(DIVIDE(TopTypeCount, Total, 0), "0%") & ")"
			)
		displayFolder: 🧠 Prompt Quality
		lineageTag: b1c2d3e4-0001-0002-0002-000000000001

	/// Dynamic narrative: how prompt characteristics correlate with session outcomes
	measure '🧠 Agent Prompt Quality Insight' =
			VAR EngagedCount = CALCULATE(COUNTROWS('Agent Performance'), 'Agent Performance'[SessionType] = "Engaged")
			VAR ResolvedCount = CALCULATE(COUNTROWS('Agent Performance'), 'Agent Performance'[SessionOutcome] = "Resolved")
			VAR AbandonedCount = CALCULATE(COUNTROWS('Agent Performance'), 'Agent Performance'[SessionOutcome] = "Abandoned")
			VAR AvgScore = [Avg Prompt Quality Score]
			
			// Prompt length analysis
			VAR AvgLenResolved = CALCULATE(AVERAGE('Agent Performance'[PromptLength]), 'Agent Performance'[SessionOutcome] = "Resolved")
			VAR AvgLenAbandoned = CALCULATE(AVERAGE('Agent Performance'[PromptLength]), 'Agent Performance'[SessionOutcome] = "Abandoned")
			
			// Turn efficiency
			VAR AvgTurnsResolved = CALCULATE(AVERAGE('Agent Performance'[TurnCount]), 'Agent Performance'[SessionOutcome] = "Resolved")
			VAR AvgTurnsAbandoned = CALCULATE(AVERAGE('Agent Performance'[TurnCount]), 'Agent Performance'[SessionOutcome] = "Abandoned")
			
			// Quick resolution rate (resolved in ≤ 3 turns)
			VAR QuickResolve = CALCULATE(COUNTROWS('Agent Performance'), 'Agent Performance'[SessionOutcome] = "Resolved", 'Agent Performance'[TurnCount] <= 3)
			VAR QuickResolvePct = DIVIDE(QuickResolve, ResolvedCount, 0)
			
			// Score line
			VAR ScoreLine = "Avg score: " & FORMAT(AvgScore, "0.0") & "/100 across " & FORMAT(EngagedCount, "#,0") & " engaged sessions."
			
			// Prompt length insight
			VAR LengthLine =
			    IF(NOT ISBLANK(AvgLenResolved) && NOT ISBLANK(AvgLenAbandoned),
			        IF(AvgLenResolved > AvgLenAbandoned * 1.15,
			            " Resolved prompts avg " & FORMAT(AvgLenResolved, "#,0") & " chars vs " & FORMAT(AvgLenAbandoned, "#,0") & " for abandoned — more detail helps.",
			            IF(AvgLenAbandoned > AvgLenResolved * 1.15,
			                " Abandoned prompts are longer (avg " & FORMAT(AvgLenAbandoned, "#,0") & " chars) — complex queries may exceed agent capability.",
			                " Prompt length similar across outcomes (~" & FORMAT(AvgLenResolved, "#,0") & " chars)."
			            )
			        ),
			        ""
			    )
			
			// Turn insight
			VAR TurnLine =
			    IF(NOT ISBLANK(AvgTurnsResolved),
			        " Resolved sessions avg " & FORMAT(AvgTurnsResolved, "0.0") & " turns" &
			        IF(NOT ISBLANK(AvgTurnsAbandoned),
			            " vs " & FORMAT(AvgTurnsAbandoned, "0.0") & " for abandoned.", "."),
			        ""
			    )
			
			// Quick resolution insight
			VAR QuickLine =
			    IF(ResolvedCount > 0,
			        " " & FORMAT(QuickResolvePct, "0%") & " of resolutions happened within 3 turns.",
			        ""
			    )
			
			RETURN
			IF(EngagedCount = 0, "No engaged sessions in current selection.",
			    ScoreLine & LengthLine & TurnLine & QuickLine
			)
		displayFolder: 🧠 Prompt Quality
		lineageTag: b1c2d3e4-0001-0001-0004-000000000001

	/// Prompt quality broken down by conversation type — shows which categories have best/worst quality
	measure '🧠 Prompt Quality by Type' =
			VAR TypeStats =
			    ADDCOLUMNS(
			        FILTER(VALUES('Agent Performance'[ConversationType]), [ConversationType] <> "🚫 Unengaged"),
			        "AvgScore", CALCULATE(AVERAGE('Agent Performance'[PromptQualityScore])),
			        "Total", CALCULATE(COUNTROWS('Agent Performance')),
			        "ResRate", DIVIDE(
			            CALCULATE(COUNTROWS('Agent Performance'), 'Agent Performance'[SessionOutcome] = "Resolved"),
			            CALCULATE(COUNTROWS('Agent Performance')), 0)
			    )
			VAR BestType = TOPN(1, FILTER(TypeStats, [Total] >= 2), [AvgScore], DESC)
			VAR WorstType = TOPN(1, FILTER(TypeStats, [Total] >= 2), [AvgScore], ASC)
			VAR BestName = MAXX(BestType, [ConversationType])
			VAR BestScore = MAXX(BestType, [AvgScore])
			VAR WorstName = MAXX(WorstType, [ConversationType])
			VAR WorstScore = MAXX(WorstType, [AvgScore])
			RETURN
			IF(COUNTROWS(TypeStats) = 0, "No data.",
			    "Best: " & BestName & " (score " & FORMAT(BestScore, "0.0") & ") | " &
			    "Weakest: " & WorstName & " (score " & FORMAT(WorstScore, "0.0") & ")"
			)
		displayFolder: 🧠 Prompt Quality
		lineageTag: b1c2d3e4-0001-0001-0005-000000000001

	/// Average turns across all conversations (effort signal) — used on Conversation Analysis
	measure 'Avg Turns' = AVERAGE('Agent Performance'[TurnCount])
		formatString: 0.0
		displayFolder: Agent KPIs
		lineageTag: c0a1b2c3-0002-0001-0001-000000000001

	/// Dynamic narrative theming conversation topics by resolution — strongest, weakest, and most-escalated topics
	measure '🧠 Topic Resolution Insight' =
			VAR T =
			    ADDCOLUMNS(
			        FILTER(
			            VALUES('Agent Performance'[Topic (resolved)]),
			            CALCULATE([Total Conversations]) >= 5
			                && ( NOT (CONTAINSSTRING('Agent Performance'[Topic (resolved)], UNICHAR(128683))) && 'Agent Performance'[Topic (resolved)] <> "Other" )
			        ),
			        "Res", DIVIDE([Resolved Conversations], CALCULATE([Total Conversations], 'Agent Performance'[SessionType] = "Engaged")),
			        "Esc", [Escalation Rate]
			    )
			VAR Best = TOPN(1, T, [Res], DESC)
			VAR Worst = TOPN(1, T, [Res], ASC)
			VAR EscR = TOPN(1, T, [Esc], DESC)
			RETURN
			IF(
			    COUNTROWS(T) = 0, "Not enough conversations to theme topics in this selection.",
			    "✅ " & MAXX(Best, 'Agent Performance'[Topic (resolved)]) & " resolves best (" & FORMAT(MAXX(Best, [Res]), "0%") & " of engaged). " &
			    "⚠️ " & MAXX(Worst, 'Agent Performance'[Topic (resolved)]) & " is the biggest drag (" & FORMAT(MAXX(Worst, [Res]), "0%") & "). " &
			    "🔁 " & MAXX(EscR, 'Agent Performance'[Topic (resolved)]) & " escalates most (" & FORMAT(MAXX(EscR, [Esc]), "0%") & ")."
			)
		displayFolder: 🗂 Topics
		lineageTag: c0a1b2c3-0002-0001-0002-000000000001

	/// Conversations the agent resolved on its own.
	measure 'Resolved Conversations' = CALCULATE([Total Conversations], 'Agent Performance'[SessionOutcome] = "Resolved")
		formatString: #,0
		displayFolder: 🗂 Topics
		lineageTag: ap0topic-meas-0001-000000000001

	/// Conversations handed off to a human.
	measure 'Escalated Conversations' = CALCULATE([Total Conversations], 'Agent Performance'[SessionOutcome] = "Escalated")
		formatString: #,0
		displayFolder: 🗂 Topics
		lineageTag: ap0topic-meas-0001-000000000002

	/// Conversations the user dropped without a resolution.
	measure 'Abandoned Conversations' = CALCULATE([Total Conversations], 'Agent Performance'[SessionOutcome] = "Abandoned")
		formatString: #,0
		displayFolder: 🗂 Topics
		lineageTag: ap0topic-meas-0001-000000000003

	/// Of conversations that reached a clear outcome (resolved OR escalated to a
	/// human), the share the agent contained itself. Drives "Best Self-Served Topics".
	measure 'Deflection Rate' = DIVIDE([Resolved Conversations], [Resolved Conversations] + [Escalated Conversations])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 🗂 Topics
		lineageTag: ap0topic-meas-0001-000000000004

	/// Share of resolved conversations the agent closed within 3 turns (fast wins).
	measure 'Quick-Resolve Rate (<=3 turns)' =
			DIVIDE(
			    CALCULATE([Total Conversations],
			        'Agent Performance'[SessionOutcome] = "Resolved",
			        'Agent Performance'[TurnCount] <= 3),
			    [Resolved Conversations])
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: 🗂 Topics
		lineageTag: ap0topic-meas-0001-000000000005

	measure '🧠 Conversation Summary' =
			VAR Total = [Total Conversations]
			VAR Engaged = CALCULATE([Total Conversations], 'Agent Performance'[SessionType] = "Engaged")
			VAR EngPct = DIVIDE(Engaged, Total)
			VAR ResEng = DIVIDE([Resolved Conversations], Engaged)
			VAR AbnEng = DIVIDE([Abandoned Conversations], Engaged)
			VAR T =
			    ADDCOLUMNS(
			        FILTER(
			            VALUES('Agent Performance'[Topic (resolved)]),
			            ( NOT (CONTAINSSTRING('Agent Performance'[Topic (resolved)], UNICHAR(128683))) && 'Agent Performance'[Topic (resolved)] <> "Other" )
			        ),
			        "V", [Total Conversations],
			        "A", [Abandonment Rate]
			    )
			VAR TopTopic = MAXX(TOPN(1, T, [V], DESC), 'Agent Performance'[Topic (resolved)])
			VAR TopVol = MAXX(TOPN(1, T, [V], DESC), [V])
			VAR WorstTopic = MAXX(TOPN(1, FILTER(T, [V] >= 5), [A], DESC), 'Agent Performance'[Topic (resolved)])
			RETURN
			IF(
			    Total = 0, "No conversations in this selection.",
			    FORMAT(Total, "#,0") & " conversations, " & FORMAT(EngPct, "0%") & " engaged. " &
			    "Among engaged: " & FORMAT(ResEng, "0%") & " resolved, " & FORMAT(AbnEng, "0%") & " abandoned. " &
			    "Busiest topic: " & TopTopic & " (" & FORMAT(TopVol, "#,0") & " convs). " &
			    "Most abandoned: " & WorstTopic & "."
			)
		displayFolder: 🗂 Topics
		lineageTag: ap0topic-meas-0001-000000000010

	measure 'Top Topic per Agent' = ```
			
			VAR T =
			    ADDCOLUMNS (
			        FILTER (
			            VALUES ( 'Agent Performance'[Topic (resolved)] ),
			            ( NOT ( CONTAINSSTRING ( 'Agent Performance'[Topic (resolved)], UNICHAR ( 128683 ) ) ) && 'Agent Performance'[Topic (resolved)] <> "Other" )
			        ),
			        "@Convs", CALCULATE ( [Total Conversations] )
			    )
			VAR Best = TOPN ( 1, T, [@Convs], DESC )
			RETURN
			    IF (
			        ISBLANK ( MAXX ( Best, [@Convs] ) ), "—",
			        MAXX ( Best, 'Agent Performance'[Topic (resolved)] )
			            & " (" & FORMAT ( MAXX ( Best, [@Convs] ), "#,0" ) & ")"
			    )
			
			```
		displayFolder: Agent KPIs
		lineageTag: c851f690-a816-4de3-8825-39de1f33a702

	/// The topic this agent RESOLVES most (by resolved-conversation count), excluding noise buckets.
	measure 'Top Resolved Topic' = ```
			
			VAR T =
			    ADDCOLUMNS (
			        FILTER (
			            VALUES ( 'Agent Performance'[Topic (resolved)] ),
			            ( NOT ( CONTAINSSTRING ( 'Agent Performance'[Topic (resolved)], UNICHAR ( 128683 ) ) ) && 'Agent Performance'[Topic (resolved)] <> "Other" )
			        ),
			        "@N", CALCULATE ( [Resolved Conversations] )
			    )
			VAR Best = TOPN ( 1, T, [@N], DESC )
			RETURN
			    IF (
			        ISBLANK ( MAXX ( Best, [@N] ) ) || MAXX ( Best, [@N] ) = 0, "—",
			        MAXX ( Best, 'Agent Performance'[Topic (resolved)] )
			            & " (" & FORMAT ( MAXX ( Best, [@N] ), "#,0" ) & ")"
			    )
			
			```
		displayFolder: Agent KPIs
		lineageTag: ap0topic-meas-topres-000000000001

	/// The topic this agent sees ABANDONED most (user dropped, no resolution), excluding noise buckets.
	measure 'Top Abandoned Topic' = ```
			
			VAR T =
			    ADDCOLUMNS (
			        FILTER (
			            VALUES ( 'Agent Performance'[Topic (resolved)] ),
			            ( NOT ( CONTAINSSTRING ( 'Agent Performance'[Topic (resolved)], UNICHAR ( 128683 ) ) ) && 'Agent Performance'[Topic (resolved)] <> "Other" )
			        ),
			        "@N", CALCULATE ( [Abandoned Conversations] )
			    )
			VAR Best = TOPN ( 1, T, [@N], DESC )
			RETURN
			    IF (
			        ISBLANK ( MAXX ( Best, [@N] ) ) || MAXX ( Best, [@N] ) = 0, "—",
			        MAXX ( Best, 'Agent Performance'[Topic (resolved)] )
			            & " (" & FORMAT ( MAXX ( Best, [@N] ), "#,0" ) & ")"
			    )
			
			```
		displayFolder: Agent KPIs
		lineageTag: ap0topic-meas-topabn-000000000002

	/// The topic this agent ESCALATES to a human most, excluding noise buckets.
	measure 'Top Escalated Topic' = ```
			
			VAR T =
			    ADDCOLUMNS (
			        FILTER (
			            VALUES ( 'Agent Performance'[Topic (resolved)] ),
			            ( NOT ( CONTAINSSTRING ( 'Agent Performance'[Topic (resolved)], UNICHAR ( 128683 ) ) ) && 'Agent Performance'[Topic (resolved)] <> "Other" )
			        ),
			        "@N", CALCULATE ( [Escalated Conversations] )
			    )
			VAR Best = TOPN ( 1, T, [@N], DESC )
			RETURN
			    IF (
			        ISBLANK ( MAXX ( Best, [@N] ) ) || MAXX ( Best, [@N] ) = 0, "—",
			        MAXX ( Best, 'Agent Performance'[Topic (resolved)] )
			            & " (" & FORMAT ( MAXX ( Best, [@N] ), "#,0" ) & ")"
			    )
			
			```
		displayFolder: Agent KPIs
		lineageTag: ap0topic-meas-topesc-000000000003

	column ConversationTranscriptId
		dataType: string
		lineageTag: 4db8c731-76cb-4736-92c2-31f8c653f79d
		summarizeBy: none
		sourceColumn: ConversationTranscriptId

		annotation SummarizationSetBy = Automatic

	column ConversationStartTime
		dataType: string
		lineageTag: 58afca0f-763c-4a3f-ad33-e64cf2285055
		summarizeBy: none
		sourceColumn: ConversationStartTime

		annotation SummarizationSetBy = Automatic

	column SchemaVersion
		dataType: string
		lineageTag: 3c5dad45-30e0-4772-9d7e-b9561bd8c468
		summarizeBy: none
		sourceColumn: SchemaVersion

		annotation SummarizationSetBy = Automatic

	column BotName
		dataType: string
		lineageTag: f701892d-5ea5-4553-a509-8c5e9f8aaa99
		summarizeBy: none
		sourceColumn: BotName

		annotation SummarizationSetBy = Automatic

	column BotId
		dataType: string
		lineageTag: 14675c6e-6d7a-45bb-a4b0-cf4d5825d8fb
		summarizeBy: none
		sourceColumn: BotId

		annotation SummarizationSetBy = Automatic

	column AADTenantId
		dataType: string
		lineageTag: b72091fc-15c6-447d-9e11-dd48aca353ba
		summarizeBy: none
		sourceColumn: AADTenantId

		annotation SummarizationSetBy = Automatic

	column BatchId
		dataType: string
		lineageTag: 9c38c1f4-fd5f-4c66-8162-52dc86c5fa6f
		summarizeBy: none
		sourceColumn: BatchId

		annotation SummarizationSetBy = Automatic

	column SessionStartTimeUtc
		dataType: dateTime
		formatString: General Date
		lineageTag: 4c87322e-68e0-43b9-91d1-3e8e27977f8a
		summarizeBy: none
		sourceColumn: SessionStartTimeUtc

		annotation SummarizationSetBy = Automatic

	column SessionEndTimeUtc
		dataType: string
		lineageTag: 075be579-242c-4186-a313-8c5850a0194a
		summarizeBy: none
		sourceColumn: SessionEndTimeUtc

		annotation SummarizationSetBy = Automatic

	column SessionType
		dataType: string
		lineageTag: 1d4fd4b7-74d4-4647-b5dc-05272074ee43
		summarizeBy: none
		sourceColumn: SessionType

		annotation SummarizationSetBy = Automatic

	column SessionOutcome
		dataType: string
		lineageTag: 5669406b-6bfe-48b5-ac20-3dadb67ac56d
		summarizeBy: none
		sourceColumn: SessionOutcome

		annotation SummarizationSetBy = Automatic

	column TurnCount
		dataType: int64
		formatString: 0
		lineageTag: 12e36bfc-ee56-4c87-afaa-3c9b3a4f57f3
		summarizeBy: sum
		sourceColumn: TurnCount

		annotation SummarizationSetBy = Automatic

	column OutcomeReason
		dataType: string
		lineageTag: f794ff7c-3262-482f-ad20-4c37a83ef6c0
		summarizeBy: none
		sourceColumn: OutcomeReason

		annotation SummarizationSetBy = Automatic

	column ImpliedSuccess
		dataType: string
		lineageTag: 7b5581e5-7dff-4d47-9d05-008a9f20fa6d
		summarizeBy: none
		sourceColumn: ImpliedSuccess

		annotation SummarizationSetBy = Automatic

	column LastUserIntentId
		dataType: string
		lineageTag: 10950fe7-fd8a-489c-8fcc-248e3a36f7c0
		summarizeBy: none
		sourceColumn: LastUserIntentId

		annotation SummarizationSetBy = Automatic

	column IsDesignMode
		dataType: string
		lineageTag: ca9a6308-0597-4ec0-8355-ab4e1c5404a0
		summarizeBy: none
		sourceColumn: IsDesignMode

		annotation SummarizationSetBy = Automatic

	column Locale
		dataType: string
		lineageTag: 51a45b72-d696-40c9-a8a9-88b89607fb7a
		summarizeBy: none
		sourceColumn: Locale

		annotation SummarizationSetBy = Automatic

	column UserMessageCount
		dataType: int64
		formatString: 0
		lineageTag: 8c8b7e11-4408-4c3a-ac19-19fd3129d2a9
		summarizeBy: sum
		sourceColumn: UserMessageCount

		annotation SummarizationSetBy = Automatic

	column BotMessageCount
		dataType: int64
		formatString: 0
		lineageTag: e73dc91f-ee1a-4197-88a9-3c20c5feade5
		summarizeBy: sum
		sourceColumn: BotMessageCount

		annotation SummarizationSetBy = Automatic

	column TotalMessageCount
		dataType: int64
		formatString: 0
		lineageTag: 9d581c95-bea3-4445-a4ce-6c912d11660c
		summarizeBy: sum
		sourceColumn: TotalMessageCount

		annotation SummarizationSetBy = Automatic

	column FirstUserMessage
		dataType: string
		lineageTag: f1216597-aa19-43f6-97bb-904c39df65c6
		summarizeBy: none
		sourceColumn: FirstUserMessage

		annotation SummarizationSetBy = Automatic

	column LastUserMessage
		dataType: string
		lineageTag: 710ba6ae-4131-4d48-ac6d-1799523cf016
		summarizeBy: none
		sourceColumn: LastUserMessage

		annotation SummarizationSetBy = Automatic

	column FirstBotMessage
		dataType: string
		lineageTag: be369f80-9ace-41e4-904f-5f60ed6eaf90
		summarizeBy: none
		sourceColumn: FirstBotMessage

		annotation SummarizationSetBy = Automatic

	column LastBotMessage
		dataType: string
		lineageTag: f8153202-d63f-48d6-9cd8-dd6bf415f2c7
		summarizeBy: none
		sourceColumn: LastBotMessage

		annotation SummarizationSetBy = Automatic

	column TopicsTriggered
		dataType: string
		lineageTag: 04c77301-136d-4530-b270-e4703d53efef
		summarizeBy: none
		sourceColumn: TopicsTriggered

		annotation SummarizationSetBy = Automatic

	column TopicCount
		dataType: int64
		formatString: 0
		lineageTag: ba4895f5-d913-4d13-a6f9-b19493f3845c
		summarizeBy: sum
		sourceColumn: TopicCount

		annotation SummarizationSetBy = Automatic

	column PrimaryTopic
		dataType: string
		lineageTag: 47532253-aaec-4e6c-ab60-52e4edb20614
		summarizeBy: none
		sourceColumn: PrimaryTopic

		annotation SummarizationSetBy = Automatic

	column DurationSeconds
		dataType: int64
		formatString: 0
		lineageTag: 34091375-37d1-437c-8b5c-3250e7b50693
		summarizeBy: sum
		sourceColumn: DurationSeconds

		annotation SummarizationSetBy = Automatic

	column AverageLatencyMs
		dataType: int64
		formatString: 0
		lineageTag: 8b4aa94f-384e-48eb-8841-66039ec977d0
		summarizeBy: sum
		sourceColumn: AverageLatencyMs

		annotation SummarizationSetBy = Automatic

	column Var_ESS_UserContext_UPN
		dataType: string
		lineageTag: fe054b90-9563-43be-8199-d36f53b14173
		summarizeBy: none
		sourceColumn: Var_ESS_UserContext_UPN

		annotation SummarizationSetBy = Automatic

	column Var_ESS_Message_Disclaimer
		dataType: string
		lineageTag: 85c91a55-d276-4bdc-91bf-562c9a7326f2
		summarizeBy: none
		sourceColumn: Var_ESS_Message_Disclaimer

		annotation SummarizationSetBy = Automatic

	column Var_ESS_UserContext_RefreshInterval_Hours
		dataType: string
		lineageTag: b837fcbf-186e-4295-9e3b-e2331159f95c
		summarizeBy: none
		sourceColumn: Var_ESS_UserContext_RefreshInterval_Hours

		annotation SummarizationSetBy = Automatic

	column Var_ESS_UserContext_Conversation_Initialized
		dataType: string
		lineageTag: b6f268d5-b737-4adb-ac66-0ce543b85e4b
		summarizeBy: none
		sourceColumn: Var_ESS_UserContext_Conversation_Initialized

		annotation SummarizationSetBy = Automatic

	column AllVariables
		dataType: string
		lineageTag: e5341a23-cd18-451b-834c-8c52c9c7a4d9
		summarizeBy: none
		sourceColumn: AllVariables

		annotation SummarizationSetBy = Automatic

	column TotalActivityCount
		dataType: int64
		formatString: 0
		lineageTag: 2a9dbb40-e2be-4a2b-8c9a-1c9f789e10b1
		summarizeBy: sum
		sourceColumn: TotalActivityCount

		annotation SummarizationSetBy = Automatic

	column TraceActivityCount
		dataType: int64
		formatString: 0
		lineageTag: e7ef4d4a-0c9f-46bf-937e-136f7f6083cd
		summarizeBy: sum
		sourceColumn: TraceActivityCount

		annotation SummarizationSetBy = Automatic

	column EventActivityCount
		dataType: int64
		formatString: 0
		lineageTag: 4ad087bb-1846-4d65-af97-25845ea29716
		summarizeBy: sum
		sourceColumn: EventActivityCount

		annotation SummarizationSetBy = Automatic

	column StatusCode
		dataType: int64
		formatString: 0
		lineageTag: 782f837f-d6c9-4850-a500-c79f301e3a95
		summarizeBy: count
		sourceColumn: StatusCode

		annotation SummarizationSetBy = Automatic

	column StateCode
		dataType: int64
		formatString: 0
		lineageTag: 4bd22a04-7a53-4d0e-b1a2-d8c836eafdd4
		summarizeBy: count
		sourceColumn: StateCode

		annotation SummarizationSetBy = Automatic

	column InteractionDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d7236bcc-5548-4f4d-98fd-1934e20738a0
		summarizeBy: none
		sourceColumn: InteractionDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column weekstart
		dataType: string
		lineageTag: be17175b-7500-489c-9c92-64f017f2858a
		summarizeBy: none
		sourceColumn: weekstart

		annotation SummarizationSetBy = Automatic

	column BotFriendlyName =
			SWITCH(
			    'Agent Performance'[BotName],
			    "msdyn_copilotforemployeeselfserviceit", "IT Self-Service",
			    "msdyn_copilotforemployeeselfservicehr", "HR Self-Service",
			    "cat_adaptiveCardGallery", "Adaptive Card Gallery",
			    'Agent Performance'[BotName]
			)
		lineageTag: a7b24cb8-02ea-4d50-bce4-3e0fb02f7d7e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ConversationType =
			VAR FirstUser = LOWER('Agent Performance'[FirstUserMessage])
			VAR TopicCount = 'Agent Performance'[TopicCount]
			VAR TurnCount = 'Agent Performance'[TurnCount]
			
			VAR Category =
			    IF(
			        TopicCount = 0,
			        "🚫 Unengaged",
			        IF(
			            TopicCount = 1 && TurnCount <= 2,
			            "⚡ Quick Info",
			            IF(
			                TopicCount >= 3,
			                "🔀 Multi-Topic",
			                IF(
			                    TurnCount >= 5,
			                    "💬 Extended",
			                    IF(
			                        CONTAINSSTRING(FirstUser, "error") ||
			                        CONTAINSSTRING(FirstUser, "issue") ||
			                        CONTAINSSTRING(FirstUser, "problem") ||
			                        CONTAINSSTRING(FirstUser, "not working") ||
			                        CONTAINSSTRING(FirstUser, "broken"),
			                        "🔧 Troubleshooting",
			                        "❓ Standard"
			                    )
			                )
			            )
			        )
			    )
			
			RETURN Category
		lineageTag: 4d9268d0-2b8d-482b-b4b1-a458228dccdb
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	/// Character count of first user message — used by Prompt Quality Score
	column PromptLength =
			IF(
			    ISBLANK('Agent Performance'[FirstUserMessage]),
			    0,
			    LEN('Agent Performance'[FirstUserMessage])
			)
		dataType: int64
		formatString: #,0
		lineageTag: b1c2d3e4-0002-0001-0001-000000000001
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Composite score (0–100) rating user prompt quality based on outcome, efficiency, errors, and specificity
	column PromptQualityScore =
			VAR IsEngaged = 'Agent Performance'[SessionType] = "Engaged"
			VAR Outcome = 'Agent Performance'[SessionOutcome]
			VAR Turns = 'Agent Performance'[TurnCount]
			VAR Reason = 'Agent Performance'[OutcomeReason]
			VAR MsgLen = 'Agent Performance'[PromptLength]
			
			// 1. Engagement (15 pts) — did the prompt engage the bot?
			VAR EngagePts = IF(IsEngaged, 15, 0)
			
			// 2. Resolution (35 pts) — ultimate success signal
			VAR ResolvePts =
			    SWITCH(Outcome,
			        "Resolved", 35,
			        "Abandoned", 5,
			        "Escalated", 15,
			        0
			    )
			
			// 3. Turn efficiency (20 pts) — fewer turns to resolve = clearer prompt
			VAR TurnPts =
			    IF(NOT IsEngaged, 0,
			        IF(Outcome = "Resolved",
			            IF(Turns <= 3, 20, IF(Turns <= 5, 15, IF(Turns <= 8, 10, 5))),
			            IF(Turns <= 2, 5,
			                IF(Turns <= 5, 8,
			                    IF(Turns <= 8, 5, 2)))
			        )
			    )
			
			// 4. Error-free (10 pts) — no system/user errors
			VAR ErrorPts =
			    IF(Reason = "SystemError", 0,
			        IF(Reason = "UserError", 3, 10)
			    )
			
			// 5. Implied success (10 pts)
			VAR SuccessPts = IF('Agent Performance'[ImpliedSuccess] = "TRUE", 10, 0)
			
			// 6. Prompt specificity (10 pts) — based on message length
			VAR SpecPts =
			    IF(MsgLen = 0, 0,
			        IF(MsgLen < 15, 2,
			            IF(MsgLen <= 40, 5,
			                IF(MsgLen <= 100, 10, 8)
			            )
			        )
			    )
			
			VAR RawScore = EngagePts + ResolvePts + TurnPts + ErrorPts + SuccessPts + SpecPts
			
			RETURN MIN(RawScore, 100)
		dataType: int64
		formatString: #,0
		lineageTag: b1c2d3e4-0002-0001-0002-000000000001
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Numeric complexity score (0–5) for averaging at agent/group level
	column ConversationComplexity =
			SWITCH(
			    'Agent Performance'[ConversationType],
			    "🚫 Unengaged", 0,
			    "⚡ Quick Info", 1,
			    "❓ Standard", 2,
			    "🔧 Troubleshooting", 3,
			    "💬 Extended", 4,
			    "🔀 Multi-Topic", 5,
			    2
			)
		dataType: int64
		formatString: 0
		lineageTag: b1c2d3e4-0002-0002-0001-000000000001
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	/// Higher-level grouping of PrimaryTopic for the Topic Themes treemap / slicer.
	/// Quick-win keyword bucketing — swap for a Topic Theme Mapping table when ready.
	column 'Topic Theme' =
			VAR t = LOWER('Agent Performance'[PrimaryTopic])
			RETURN
			    SWITCH(
			        TRUE(),
			        CONTAINSSTRING(t, "password") || CONTAINSSTRING(t, "mfa") || CONTAINSSTRING(t, "login") || CONTAINSSTRING(t, "access"), "IT & Access",
			        CONTAINSSTRING(t, "payroll") || CONTAINSSTRING(t, "expense") || CONTAINSSTRING(t, "pension") || CONTAINSSTRING(t, "payslip"), "Finance",
			        CONTAINSSTRING(t, "leave") || CONTAINSSTRING(t, "holiday") || CONTAINSSTRING(t, "absence") || CONTAINSSTRING(t, "onboard"), "HR & People",
			        CONTAINSSTRING(t, "policy") || CONTAINSSTRING(t, "compliance") || CONTAINSSTRING(t, "benefit"), "Policy",
			        ISBLANK(t) || t = "", "Untagged",
			        "Other"
			    )
		lineageTag: ap0topic-col0-0001-000000000001
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Topic (resolved)' =
			VAR classic = 'Agent Performance'[PrimaryTopic]
			VAR lc = LOWER(classic)
			VAR isSystemClassic = CONTAINSSTRING(lc, "[system]") || lc = "logging" || lc = "greeting" || CONTAINSSTRING(lc, "conversation start")
			VAR m = LOWER(TRIM('Agent Performance'[FirstUserMessage]))
			VAR derived =
			    SWITCH(
			        TRUE(),
			        ISBLANK(m) || m = "", "🚫 No message",
			        CONTAINSSTRING(m, "have access to talk to this bot") || CONTAINSSTRING(m, "contact the owner"), "🚫 No Access (system)",
			        LEFT(m, 1) = "/", "🚫 Command",
			        m IN {"hi", "hey", "hello", "test", "ok", "thanks", "thank you"}, "🚫 Greeting",
			        CONTAINSSTRING(m, "what this agent can do") || CONTAINSSTRING(m, "what can you do") || CONTAINSSTRING(m, "example of what"), "🚫 Capability probe",
			        CONTAINSSTRING(m, "suicid") || CONTAINSSTRING(m, "harm myself") || CONTAINSSTRING(m, "kill myself"), "⚠ Safety / Wellbeing",
			        CONTAINSSTRING(m, "threat") || CONTAINSSTRING(m, "scare") || CONTAINSSTRING(m, "ignore previous") || CONTAINSSTRING(m, "pretend you"), "⚠ Misuse / Jailbreak",
			        CONTAINSSTRING(m, "is this valid") || CONTAINSSTRING(m, "is this correct"), "⚠ PII / Validation",
			        CONTAINSSTRING(m, "leave") || CONTAINSSTRING(m, "holiday") || CONTAINSSTRING(m, "absence") || CONTAINSSTRING(m, "redundancy"), "Leave & Absence",
			        CONTAINSSTRING(m, "access") || CONTAINSSTRING(m, "permission") || CONTAINSSTRING(m, "carm") || CONTAINSSTRING(m, "login") || CONTAINSSTRING(m, "password") || CONTAINSSTRING(m, "iga"), "Access & Permissions",
			        CONTAINSSTRING(m, "laptop") || CONTAINSSTRING(m, "order") || CONTAINSSTRING(m, "device") || CONTAINSSTRING(m, "phone") || CONTAINSSTRING(m, "holder"), "Device & Hardware",
			        CONTAINSSTRING(m, "licen") || CONTAINSSTRING(m, "mural") || CONTAINSSTRING(m, "vpl") || CONTAINSSTRING(m, "power bi") || CONTAINSSTRING(m, "install"), "Software & Licensing",
			        CONTAINSSTRING(m, "who is") || CONTAINSSTRING(m, "directory") || CONTAINSSTRING(m, "hidden") || CONTAINSSTRING(m, "contact number"), "People & Directory",
			        CONTAINSSTRING(m, "pay") || CONTAINSSTRING(m, "bonus") || CONTAINSSTRING(m, "expense") || CONTAINSSTRING(m, "payslip") || CONTAINSSTRING(m, "uplift") || CONTAINSSTRING(m, "amex"), "Pay & Expenses",
			        CONTAINSSTRING(m, "purchas") || CONTAINSSTRING(m, "flexpay") || CONTAINSSTRING(m, "hub") || CONTAINSSTRING(m, "parking") || CONTAINSSTRING(m, "discount"), "Purchasing & Perks",
			        CONTAINSSTRING(m, "contract") || CONTAINSSTRING(m, "policy") || CONTAINSSTRING(m, "documentation") || CONTAINSSTRING(m, "process") || CONTAINSSTRING(m, "terms"), "Policy & Process",
			        "Other"
			    )
			RETURN
			    IF(NOT isSystemClassic && NOT ISBLANK(classic) && classic <> "", classic, derived)
		lineageTag: ap0topic-col0-0001-000000000002
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Agent Performance' = m
		mode: import
		source =
				let
				    // CT-derived agent performance, produced by the transcript parser
				    // (parse_copilot_transcripts.py / Copilot_Agent_Transcript_Parser.ipynb)
				    // alongside agent_sessions.csv etc. in the same Lakehouse folder.
				    PromotedHeaders = if Enable_Dataverse = "Include" then (try FabricTable("agent_performance") otherwise EmptyTable({"ConversationTranscriptId", "ConversationStartTime", "SchemaVersion", "BotName", "BotId", "AADTenantId", "BatchId", "SessionStartTimeUtc", "SessionEndTimeUtc", "SessionType", "SessionOutcome", "TurnCount", "OutcomeReason", "ImpliedSuccess", "LastUserIntentId", "IsDesignMode", "Locale", "UserMessageCount", "BotMessageCount", "TotalMessageCount", "FirstUserMessage", "LastUserMessage", "FirstBotMessage", "LastBotMessage", "TopicsTriggered", "TopicCount", "PrimaryTopic", "DurationSeconds", "AverageLatencyMs", "Var_ESS_UserContext_UPN", "Var_ESS_Message_Disclaimer", "Var_ESS_UserContext_RefreshInterval_Hours", "Var_ESS_UserContext_Conversation_Initialized", "AllVariables", "TotalActivityCount", "TraceActivityCount", "EventActivityCount", "StatusCode", "StateCode"})) else EmptyTable({"ConversationTranscriptId", "ConversationStartTime", "SchemaVersion", "BotName", "BotId", "AADTenantId", "BatchId", "SessionStartTimeUtc", "SessionEndTimeUtc", "SessionType", "SessionOutcome", "TurnCount", "OutcomeReason", "ImpliedSuccess", "LastUserIntentId", "IsDesignMode", "Locale", "UserMessageCount", "BotMessageCount", "TotalMessageCount", "FirstUserMessage", "LastUserMessage", "FirstBotMessage", "LastBotMessage", "TopicsTriggered", "TopicCount", "PrimaryTopic", "DurationSeconds", "AverageLatencyMs", "Var_ESS_UserContext_UPN", "Var_ESS_Message_Disclaimer", "Var_ESS_UserContext_RefreshInterval_Hours", "Var_ESS_UserContext_Conversation_Initialized", "AllVariables", "TotalActivityCount", "TraceActivityCount", "EventActivityCount", "StatusCode", "StateCode"}),
				    ChangedTypes = Table.TransformColumnTypes(
				        PromotedHeaders,
				        {
				            {"TurnCount", Int64.Type},
				            {"UserMessageCount", Int64.Type},
				            {"BotMessageCount", Int64.Type},
				            {"TotalMessageCount", Int64.Type},
				            {"TopicCount", Int64.Type},
				            {"DurationSeconds", Int64.Type},
				            {"AverageLatencyMs", Int64.Type},
				            {"TotalActivityCount", Int64.Type},
				            {"TraceActivityCount", Int64.Type},
				            {"EventActivityCount", Int64.Type},
				            {"StatusCode", Int64.Type},
				            {"StateCode", Int64.Type}
				        }
				    ),
				    FixedSessionStartTimeUtc = Table.TransformColumns(
				        ChangedTypes,
				        {{"SessionStartTimeUtc", each try DateTime.From(_) otherwise null, type nullable datetime}}
				    ),
				    AddedInteractionDate = Table.AddColumn(
				        FixedSessionStartTimeUtc,
				        "InteractionDate",
				        each if [SessionStartTimeUtc] <> null then Date.From([SessionStartTimeUtc]) else null,
				        type nullable date
				    ),
				    AddedWeekStart = Table.AddColumn(
				        AddedInteractionDate,
				        "weekstart",
				        each if [InteractionDate] <> null then Date.ToText(Date.StartOfWeek([InteractionDate]), "MM/dd/yyyy") else null,
				        type nullable text
				    )
				in
				    AddedWeekStart

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

