/// Dimension table for Copilot Studio agents seen in the parsed transcripts.
/// Built by parse_copilot_transcripts.py — in Fabric this comes from the
/// lakehouse Delta table `agent_catalogue`.
table 'Agent Catalogue'
	lineageTag: ac0001ag-0001-0001-0001-000000000001

	column agent_schema
		dataType: string
		isKey
		lineageTag: ac0001ag-col0-0001-0001-000000000001
		summarizeBy: none
		sourceColumn: agent_schema

		annotation SummarizationSetBy = Automatic

	column agent_display_name
		dataType: string
		lineageTag: ac0001ag-col0-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: agent_display_name

		annotation SummarizationSetBy = Automatic

	column agent_class
		dataType: string
		lineageTag: ac0001ag-col0-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: agent_class

		annotation SummarizationSetBy = Automatic

	partition 'Agent Catalogue' = m
		mode: import
		source =
				let
				    Promoted = if Enable_Dataverse = "Include" then (try FabricTable("agent_catalogue") otherwise EmptyTable({"agent_schema", "agent_display_name", "agent_class"})) else EmptyTable({"agent_schema", "agent_display_name", "agent_class"}),
				    Typed = Table.TransformColumnTypes(Promoted, {
				        {"agent_schema", type text},
				        {"agent_display_name", type text},
				        {"agent_class", type text}
				    })
				in
				    Typed

	annotation PBI_ResultType = Table

