table 'Behavior Value Map'
	lineageTag: ff050001-0001-0001-0001-000000000001

	column Signal
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000002
		summarizeBy: none
		sourceColumn: Signal

		annotation SummarizationSetBy = Automatic

	column Behavior
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000003
		summarizeBy: none
		sourceColumn: Behavior

		annotation SummarizationSetBy = Automatic

	column 'Use Case'
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000004
		summarizeBy: none
		sourceColumn: Use Case

		annotation SummarizationSetBy = Automatic

	column 'Value Outcome'
		dataType: string
		lineageTag: ff050001-0001-0001-0001-000000000005
		summarizeBy: none
		sourceColumn: Value Outcome

		annotation SummarizationSetBy = Automatic

	partition 'Behavior Value Map' = m
		mode: import
		source =
				let
				    Source = #table(
				        {"Signal", "Behavior", "Use Case", "Value Outcome"},
				        {
				            // ─── COMMUNICATION (Email + Teams) ───
				            {"Outlook/OutlookSidepane + Send/Draft + EmailMessage", "Email Drafting", "Composing replies, cold outreach, formal correspondence", "Time Saved (Email)"},
				            {"Outlook/OutlookSidepane + EmailMessage + Read", "Email Summarising", "Triaging inbox, summarising threads, catching up after leave", "Time Saved (Email)"},
				            {"TeamsMessage/TeamsChat/TeamsChannel + Post/CreateChat", "Teams Messaging", "Team coordination, quick decisions, status updates", "Communication Time Saved"},
				
				            // ─── MEETINGS ───
				            {"Event/TeamsMeeting + Read", "Meeting Prep", "Reviewing agendas, catching up on missed meetings, recap summaries", "Time Saved (Meetings)"},
				            {"Action = mcp_MeetingManagement", "Meeting Scheduling", "Calendar management, finding availability, booking rooms", "Communication Time Saved"},
				
				            // ─── CONTENT CREATION ───
				            {"Word AppHost + Post/Write/Create", "Document Drafting", "Reports, proposals, briefs, documentation", "Content Output"},
				            {"Word AppHost + docx/doc/rtf + Read", "Document Summarising", "Executive summaries, long doc digests, research synthesis", "Time Saved (Documents)"},
				            {"PowerPoint AppHost + Post/Write/Create", "Presentation Creation", "Slide decks, pitch materials, training content", "Content Output"},
				            {"PowerPoint AppHost + pptx/ppt/potx + Read", "Presentation Summarising", "Deck reviews, extracting key points", "Time Saved (Documents)"},
				            {"Designer AppHost OR png/jpg/svg + Active", "Image Generation", "Marketing visuals, presentations, social content", "Content Output"},
				            {"png/jpg/gif + Read", "Image / Media Analysis", "Accessibility descriptions, content cataloguing, image review", "Content Output"},
				            {"Stream AppHost + mp4/mov/StreamVideo", "Video Summarising", "Meeting recordings, training videos, podcast recaps", "Time Saved (Meetings)"},
				
				            // ─── KNOWLEDGE & SEARCH ───
				            {"WebSearchQuery resource type", "Web Searching", "Market research, fact-checking, competitive analysis", "Search Time Saved"},
				            {"EnterpriseSearch plugin + aspx/ListItem", "Enterprise Searching", "Finding internal docs, policy lookup, knowledge retrieval", "Search Time Saved"},
				            {"PDF resource + Read", "PDF Analysis", "Contract review, report analysis, compliance checking", "Search Time Saved"},
				            {"SharePoint AppHost", "SharePoint Access", "Site browsing, file discovery, team content", "Search Time Saved"},
				            {"docx/pptx + Read (outside native app)", "File Retrieval", "Cross-referencing documents, gathering context in M365 Chat", "Search Time Saved"},
				            {"PeopleInferenceAnswer resource", "People Lookup", "Org navigation, finding experts, team-building", "Search Time Saved"},
				
				            // ─── DATA & ANALYSIS ───
				            {"Excel AppHost + ExecuteDatasetQuery/GetItems/GetAllTables", "Data Querying", "Building reports, answering data questions, KPI tracking", "Data-Driven Decisions"},
				            {"Excel AppHost + Active actions", "Excel Assistance", "Formulas, formatting, ad-hoc analysis inside Excel", "Spreadsheet Time Saved"},
				            {"xlsx/csv/xlsm + Read", "Spreadsheet Review", "Reviewing spreadsheets, validating numbers, light analysis", "Spreadsheet Time Saved"},
				
				            // ─── TECHNICAL ───
				            {"py/js/java/tsx/jsx/css/php/sh + Active", "Code Writing", "Feature development, scripting, automation", "Coding Capability"},
				            {"py/sql/json/xml/yaml/yml + Read OR coding URLs (github, stackoverflow, etc.)", "Code Analysis", "Code review, debugging, understanding codebases", "Coding Capability"},
				            {"Flow/Connector/http + Invoke", "Running a Workflow", "Automating approvals, notifications, data flows, Power Automate triggers", "Workflow Triggered"},
				
				            // ─── COLLABORATION & PRODUCTIVITY ───
				            {"OneNote AppHost", "Note Taking", "Meeting notes, personal knowledge management", "Time Saved (Documents)"},
				            {"Forms AppHost", "Form / Survey Work", "Feedback collection, quizzes, data gathering", "Team Collaboration"},
				            {"Planner AppHost + PlanId/TaskIds", "Task Management", "Sprint planning, task tracking, project coordination", "Task Coordination"},
				            {"Loop/Whiteboard/VivaEngage AppHost", "Real-time Collaboration", "Brainstorming, shared editing, team ideation", "Team Collaboration"},
				
				            // ─── AGENT CLASSIFICATIONS (Behavior_Enriched + _Full) ───
				            {"Agent name: coach/mentor/learning/career OR learning URLs", "Agent: Coaching", "Writing coaching, prompt improvement, career guidance, training", "Skills Development"},
				            {"Agent name: research/analyst/analy/insight/intelligence", "Agent: Research & Analysis", "Market research, competitive analysis, data interpretation, trend spotting", "Data-Driven Decisions"},
				            {"Agent name: sales/commercial/customer/crm/revenue OR dynamics.com URLs", "Agent: Sales & Customer", "Sales intelligence, customer insights, deal support, CRM assistance", "Revenue Enablement"},
				            {"Agent name: hr/recruit/talent/onboard/people OR description matches", "Agent: HR & People", "Job descriptions, candidate screening, onboarding guidance, policy Q&A", "HR Process Automation"},
				            {"Agent name: policy/compliance/legal/audit/risk", "Agent: Compliance & Policy", "Policy lookup, compliance checking, risk assessment, audit support", "Compliance & Risk"},
				            {"Agent name: service/support/help/ticket/incident OR servicenow.com URLs", "Agent: IT & Service Desk", "IT troubleshooting, ticket creation, knowledge base queries", "Service Desk Deflection"},
				            {"Agent name: summar/draft/translat/editor", "Agent: Content Generation", "Drafting communications, summarising documents, translation", "Content Output"},
				            {"Agent name: data/report/dashboard/metric OR has code interpreter", "Agent: Data & Reporting", "Building reports, querying data, KPI tracking, dashboard creation", "Data-Driven Decisions"},
				            {"Agent name: knowledge/faq/wiki/buddy/guide OR has SharePoint access", "Agent: Knowledge Base", "Policy lookup, process guidance, FAQ resolution, documentation search", "Search Time Saved"},
				            {"Agent name: idea/brainstorm/creative/design OR has image generation", "Agent: Ideation & Creative", "Brainstorming, design concepts, creative briefs, innovation workshops", "Content Output"},
				            {"Agent — no keyword/capability match", "Agent: General Purpose", "Unclassified agent interactions — review agent metadata for better categorisation", "General AI Productivity"},
				
				            // ─── OTHER ───
				            {"AppHost = Copilot Studio", "Domain-Specific Agent", "Specialist agent built in Copilot Studio for one function", "Specialist Expertise"},
				            {"No specific resource/plugin/action signals matched", "General Chat", "General Q&A or conversational usage without document grounding", "General AI Productivity"}
				        }
				    ),
				    #"Changed Type" = Table.TransformColumnTypes(Source, {
				        {"Signal", type text},
				        {"Behavior", type text},
				        {"Use Case", type text},
				        {"Value Outcome", type text}
				    })
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

